const categories = [
  {
    name: 'Makeup',
    description: 'Foundations, lipsticks, eyeshadows and more for a flawless look.',
    image: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Skincare',
    description: 'Serums, creams and masks to nourish and protect your skin.',
    image: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Haircare',
    description: 'Shampoos, serums and treatments for healthy, radiant hair.',
    image: 'https://images.unsplash.com/photo-1527799820374-dcf8d9d4a388?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Fragrance',
    description: 'Perfumes and eau de parfums for every occasion.',
    image: 'https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Body Care',
    description: 'Lotions, scrubs and butters for soft, glowing skin.',
    image: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Beauty Tools',
    description: 'Brushes, applicators and gadgets for the perfect routine.',
    image: 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796?auto=format&fit=crop&w=800&q=80',
  },
];

const products = [
  // ---------- Makeup ----------
  {
    name: 'Matte Liquid Foundation',
    brand: 'LUMÉA',
    category: 'Makeup',
    subcategory: 'Face',
    description:
      'A lightweight, full-coverage liquid foundation with a soft matte finish that lasts up to 12 hours without caking or settling into fine lines.',
    shortDescription: '12-hour full coverage matte foundation',
    price: 899,
    originalPrice: 1099,
    discountPercentage: 18,
    rating: 4.5,
    reviewCount: 328,
    image: 'https://images.unsplash.com/photo-1631730359585-38a4935cbec4?auto=format&fit=crop&w=800&q=80',
    thumbnail: 'https://images.unsplash.com/photo-1631730359585-38a4935cbec4?auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1631730359585-38a4935cbec4?auto=format&fit=crop&w=800&q=80'],
    shades: ['Ivory', 'Beige', 'Sand', 'Honey', 'Caramel', 'Espresso'],
    sizes: ['30ml'],
    ingredients: ['Water', 'Dimethicone', 'Titanium Dioxide', 'Glycerin'],
    benefits: ['Full coverage', 'Oil control', 'Long-lasting'],
    howToUse: 'Apply with a damp beauty sponge or brush, building coverage as needed.',
    skinType: ['Oily', 'Combination'],
    stock: 145,
    sku: 'LUM-MK-001',
    tags: ['foundation', 'matte', 'face'],
    isFeatured: true,
    isBestSeller: true,
    isNew: false,
  },
  {
    name: 'Rose Velvet Lipstick',
    brand: 'LUMÉA',
    category: 'Makeup',
    subcategory: 'Lips',
    description:
      'A creamy, high-pigment lipstick in a romantic rose shade that glides on smoothly for a velvety matte finish without drying out lips.',
    shortDescription: 'Creamy matte lipstick in romantic rose',
    price: 449,
    originalPrice: 549,
    discountPercentage: 18,
    rating: 4.6,
    reviewCount: 512,
    image: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?auto=format&fit=crop&w=800&q=80',
    thumbnail: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1586495777744-4413f21062fa?auto=format&fit=crop&w=800&q=80'],
    shades: ['Rose Velvet', 'Coral Bloom', 'Berry Crush', 'Nude Petal'],
    sizes: ['3.5g'],
    ingredients: ['Vitamin E', 'Shea Butter', 'Jojoba Oil'],
    benefits: ['Long-wear', 'Non-drying', 'High pigmentation'],
    howToUse: 'Apply directly from the bullet, starting from the center of the lips.',
    skinType: [],
    stock: 210,
    sku: 'LUM-MK-002',
    tags: ['lipstick', 'matte', 'lips'],
    isFeatured: true,
    isBestSeller: true,
    isNew: false,
  },
  {
    name: 'Nude Eyeshadow Palette',
    brand: 'LUMÉA',
    category: 'Makeup',
    subcategory: 'Eyes',
    description:
      'A versatile 12-shade eyeshadow palette featuring warm nude and bronze tones with a blend of matte and shimmer finishes for everyday to evening looks.',
    shortDescription: '12-shade matte and shimmer nude palette',
    price: 1299,
    originalPrice: 1599,
    discountPercentage: 19,
    rating: 4.7,
    reviewCount: 276,
    image: 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796?auto=format&fit=crop&w=800&q=80',
    thumbnail: 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796?auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1512496015851-a90fb38ba796?auto=format&fit=crop&w=800&q=80'],
    shades: [],
    sizes: ['12 x 1.1g'],
    ingredients: ['Mica', 'Talc', 'Dimethicone'],
    benefits: ['Highly blendable', 'Buildable pigment', 'Crease-resistant'],
    howToUse: 'Use lighter shades on the lid and deeper tones in the crease for definition.',
    skinType: [],
    stock: 98,
    sku: 'LUM-MK-003',
    tags: ['eyeshadow', 'palette', 'nude'],
    isFeatured: true,
    isBestSeller: false,
    isNew: true,
  },
  {
    name: 'Waterproof Mascara',
    brand: 'LUMÉA',
    category: 'Makeup',
    subcategory: 'Eyes',
    description:
      'A smudge-proof, waterproof mascara that lengthens and volumizes lashes for a dramatic look that lasts all day without flaking.',
    shortDescription: 'Smudge-proof volumizing mascara',
    price: 549,
    originalPrice: 649,
    discountPercentage: 15,
    rating: 4.4,
    reviewCount: 401,
    image: 'https://images.unsplash.com/photo-1591360236480-4ed861025fa1?auto=format&fit=crop&w=800&q=80',
    thumbnail: 'https://images.unsplash.com/photo-1591360236480-4ed861025fa1?auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1591360236480-4ed861025fa1?auto=format&fit=crop&w=800&q=80'],
    shades: ['Black', 'Brown Black'],
    sizes: ['9ml'],
    ingredients: ['Beeswax', 'Carnauba Wax', 'Panthenol'],
    benefits: ['Waterproof', 'Volumizing', 'Flake-free'],
    howToUse: 'Wiggle the wand at the base of lashes and sweep upward.',
    skinType: [],
    stock: 176,
    sku: 'LUM-MK-004',
    tags: ['mascara', 'eyes', 'waterproof'],
    isFeatured: false,
    isBestSeller: true,
    isNew: false,
  },
  {
    name: 'Silk Finish Compact Powder',
    brand: 'LUMÉA',
    category: 'Makeup',
    subcategory: 'Face',
    description:
      'A finely milled pressed powder that sets makeup with a soft-focus finish while controlling shine throughout the day.',
    shortDescription: 'Soft-focus setting powder',
    price: 649,
    originalPrice: 749,
    discountPercentage: 13,
    rating: 4.3,
    reviewCount: 189,
    image: 'https://images.unsplash.com/photo-1503236823255-94609f598e71?auto=format&fit=crop&w=800&q=80',
    thumbnail: 'https://images.unsplash.com/photo-1503236823255-94609f598e71?auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1503236823255-94609f598e71?auto=format&fit=crop&w=800&q=80'],
    shades: ['Translucent', 'Light', 'Medium'],
    sizes: ['12g'],
    ingredients: ['Talc', 'Silica', 'Mica'],
    benefits: ['Oil control', 'Soft-focus finish', 'Lightweight'],
    howToUse: 'Press onto skin with a puff to set makeup and control shine.',
    skinType: ['Oily', 'Combination'],
    stock: 132,
    sku: 'LUM-MK-005',
    tags: ['powder', 'setting', 'face'],
    isFeatured: false,
    isBestSeller: false,
    isNew: false,
  },
  {
    name: 'Precision Liquid Eyeliner',
    brand: 'LUMÉA',
    category: 'Makeup',
    subcategory: 'Eyes',
    description:
      'An ultra-fine felt-tip liquid eyeliner that delivers crisp, precise lines with intense black pigment in a single stroke.',
    shortDescription: 'Fine-tip intense black eyeliner',
    price: 349,
    originalPrice: 399,
    discountPercentage: 13,
    rating: 4.5,
    reviewCount: 244,
    image: 'https://images.unsplash.com/photo-1583241800698-9c2e2f4f6c7d?auto=format&fit=crop&w=800&q=80',
    thumbnail: 'https://images.unsplash.com/photo-1583241800698-9c2e2f4f6c7d?auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1583241800698-9c2e2f4f6c7d?auto=format&fit=crop&w=800&q=80'],
    shades: ['Jet Black'],
    sizes: ['0.6ml'],
    ingredients: ['Water', 'Acrylates Copolymer', 'Carbon Black'],
    benefits: ['Smudge-proof', 'Precise tip', 'Quick-dry'],
    howToUse: 'Draw a thin line along the lash line, building thickness as desired.',
    skinType: [],
    stock: 160,
    sku: 'LUM-MK-006',
    tags: ['eyeliner', 'eyes', 'liquid'],
    isFeatured: false,
    isBestSeller: false,
    isNew: true,
  },
  {
    name: 'Dewy Glow Highlighter',
    brand: 'LUMÉA',
    category: 'Makeup',
    subcategory: 'Face',
    description:
      'A silky pressed highlighter that melts into skin for a natural, lit-from-within glow on cheekbones, brow bones and collarbones.',
    shortDescription: 'Natural lit-from-within highlighter',
    price: 599,
    originalPrice: 699,
    discountPercentage: 14,
    rating: 4.6,
    reviewCount: 167,
    image: 'https://images.unsplash.com/photo-1596704017254-9b121068fb31?auto=format&fit=crop&w=800&q=80',
    thumbnail: 'https://images.unsplash.com/photo-1596704017254-9b121068fb31?auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1596704017254-9b121068fb31?auto=format&fit=crop&w=800&q=80'],
    shades: ['Champagne Glow', 'Rose Gold', 'Sunlit Amber'],
    sizes: ['8g'],
    ingredients: ['Mica', 'Dimethicone', 'Vitamin E'],
    benefits: ['Buildable glow', 'Finely milled', 'Blendable'],
    howToUse: 'Sweep onto the high points of the face with a fan brush.',
    skinType: [],
    stock: 121,
    sku: 'LUM-MK-007',
    tags: ['highlighter', 'glow', 'face'],
    isFeatured: false,
    isBestSeller: false,
    isNew: false,
  },
  {
    name: 'Sculpt & Define Contour Kit',
    brand: 'LUMÉA',
    category: 'Makeup',
    subcategory: 'Face',
    description:
      'A three-shade contour and highlight kit designed to sculpt, define and add dimension to the face with seamlessly blendable powders.',
    shortDescription: '3-shade contour and highlight kit',
    price: 899,
    originalPrice: 1099,
    discountPercentage: 18,
    rating: 4.4,
    reviewCount: 143,
    image: 'https://images.unsplash.com/photo-1522337660859-02fbefca4702?auto=format&fit=crop&w=800&q=80',
    thumbnail: 'https://images.unsplash.com/photo-1522337660859-02fbefca4702?auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1522337660859-02fbefca4702?auto=format&fit=crop&w=800&q=80'],
    shades: ['Light-Medium', 'Medium-Deep'],
    sizes: ['18g'],
    ingredients: ['Talc', 'Mica', 'Silica'],
    benefits: ['Sculpting', 'Blendable', 'Buildable'],
    howToUse: 'Apply the darker shade below cheekbones and the lighter shade above for lift.',
    skinType: [],
    stock: 84,
    sku: 'LUM-MK-008',
    tags: ['contour', 'highlight', 'face'],
    isFeatured: false,
    isBestSeller: false,
    isNew: false,
  },

  // ---------- Skincare ----------
  {
    name: 'Hydrating Glow Serum',
    brand: 'LUMÉA',
    category: 'Skincare',
    subcategory: 'Serum',
    description:
      'A lightweight hyaluronic acid serum that deeply hydrates and plumps skin, restoring a radiant, dewy glow within days of consistent use.',
    shortDescription: 'Hyaluronic acid serum for plump, glowing skin',
    price: 799,
    originalPrice: 999,
    discountPercentage: 20,
    rating: 4.7,
    reviewCount: 612,
    image: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=800&q=80',
    thumbnail: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=800&q=80'],
    shades: [],
    sizes: ['30ml'],
    ingredients: ['Hyaluronic Acid', 'Niacinamide', 'Glycerin', 'Aloe Vera'],
    benefits: ['Deep hydration', 'Plumps skin', 'Non-greasy'],
    howToUse: 'Apply 2-3 drops to cleansed skin morning and night before moisturizer.',
    skinType: ['Dry', 'Normal', 'Combination'],
    stock: 220,
    sku: 'LUM-SK-001',
    tags: ['serum', 'hydration', 'hyaluronic acid'],
    isFeatured: true,
    isBestSeller: true,
    isNew: false,
  },
  {
    name: 'Vitamin C Brightening Cream',
    brand: 'LUMÉA',
    category: 'Skincare',
    subcategory: 'Moisturizer',
    description:
      'A vitamin C-infused moisturizer that brightens dull skin, fades dark spots and evens out skin tone while providing all-day hydration.',
    shortDescription: 'Vitamin C moisturizer for brighter skin',
    price: 899,
    originalPrice: 1099,
    discountPercentage: 18,
    rating: 4.6,
    reviewCount: 487,
    image: 'https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?auto=format&fit=crop&w=800&q=80',
    thumbnail: 'https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?auto=format&fit=crop&w=800&q=80'],
    shades: [],
    sizes: ['50g'],
    ingredients: ['Vitamin C', 'Niacinamide', 'Shea Butter'],
    benefits: ['Brightens skin', 'Fades dark spots', 'Antioxidant protection'],
    howToUse: 'Massage a small amount onto face and neck every morning.',
    skinType: ['Dull', 'Uneven Tone'],
    stock: 190,
    sku: 'LUM-SK-002',
    tags: ['vitamin c', 'brightening', 'moisturizer'],
    isFeatured: true,
    isBestSeller: true,
    isNew: false,
  },
  {
    name: 'Radiance Face Mask',
    brand: 'LUMÉA',
    category: 'Skincare',
    subcategory: 'Mask',
    description:
      'A clay-based weekly treatment mask that draws out impurities, minimizes pores and leaves skin looking refreshed and radiant.',
    shortDescription: 'Weekly clay mask for radiant skin',
    price: 649,
    originalPrice: 799,
    discountPercentage: 19,
    rating: 4.5,
    reviewCount: 298,
    image: 'https://images.unsplash.com/photo-1567928815104-b7980ee5032e?auto=format&fit=crop&w=800&q=80',
    thumbnail: 'https://images.unsplash.com/photo-1567928815104-b7980ee5032e?auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1567928815104-b7980ee5032e?auto=format&fit=crop&w=800&q=80'],
    shades: [],
    sizes: ['75g'],
    ingredients: ['Kaolin Clay', 'Charcoal', 'Tea Tree Oil'],
    benefits: ['Detoxifies', 'Minimizes pores', 'Refreshes skin'],
    howToUse: 'Apply an even layer, leave for 10-15 minutes, then rinse with warm water.',
    skinType: ['Oily', 'Combination'],
    stock: 154,
    sku: 'LUM-SK-003',
    tags: ['mask', 'clay', 'detox'],
    isFeatured: false,
    isBestSeller: false,
    isNew: false,
  },
  {
    name: 'Lip Glow Oil',
    brand: 'LUMÉA',
    category: 'Skincare',
    subcategory: 'Lip Care',
    description:
      'A nourishing lip oil that conditions and adds a subtle glossy tint, leaving lips soft, hydrated and healthy-looking.',
    shortDescription: 'Nourishing tinted lip oil',
    price: 599,
    originalPrice: 699,
    discountPercentage: 14,
    rating: 4.6,
    reviewCount: 356,
    image: 'https://images.unsplash.com/photo-1625093742435-6fa192b6fb10?auto=format&fit=crop&w=800&q=80',
    thumbnail: 'https://images.unsplash.com/photo-1625093742435-6fa192b6fb10?auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1625093742435-6fa192b6fb10?auto=format&fit=crop&w=800&q=80'],
    shades: ['Sheer Rose', 'Peach Glow', 'Berry Tint'],
    sizes: ['7ml'],
    ingredients: ['Jojoba Oil', 'Vitamin E', 'Shea Butter'],
    benefits: ['Deep conditioning', 'Subtle tint', 'Non-sticky'],
    howToUse: 'Sweep the wand over lips for an instant boost of shine and hydration.',
    skinType: [],
    stock: 205,
    sku: 'LUM-SK-004',
    tags: ['lip oil', 'lip care', 'tinted'],
    isFeatured: true,
    isBestSeller: false,
    isNew: true,
  },
  {
    name: 'Gentle Foaming Cleanser',
    brand: 'LUMÉA',
    category: 'Skincare',
    subcategory: 'Cleanser',
    description:
      'A sulfate-free foaming cleanser that gently removes dirt, oil and makeup without stripping skin of its natural moisture barrier.',
    shortDescription: 'Sulfate-free daily foaming cleanser',
    price: 449,
    originalPrice: 549,
    discountPercentage: 18,
    rating: 4.5,
    reviewCount: 421,
    image: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80',
    thumbnail: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80'],
    shades: [],
    sizes: ['120ml'],
    ingredients: ['Coconut-derived Surfactants', 'Aloe Vera', 'Glycerin'],
    benefits: ['Gentle cleansing', 'Maintains moisture barrier', 'Sulfate-free'],
    howToUse: 'Massage onto damp skin, work into a lather, then rinse thoroughly.',
    skinType: ['All'],
    stock: 260,
    sku: 'LUM-SK-005',
    tags: ['cleanser', 'foaming', 'gentle'],
    isFeatured: false,
    isBestSeller: true,
    isNew: false,
  },
  {
    name: 'Retinol Night Repair Cream',
    brand: 'LUMÉA',
    category: 'Skincare',
    subcategory: 'Moisturizer',
    description:
      'A nightly treatment cream with encapsulated retinol that smooths fine lines, refines texture and supports overnight skin renewal.',
    shortDescription: 'Overnight retinol renewal cream',
    price: 1199,
    originalPrice: 1449,
    discountPercentage: 17,
    rating: 4.4,
    reviewCount: 178,
    image: 'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?auto=format&fit=crop&w=800&q=80',
    thumbnail: 'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?auto=format&fit=crop&w=800&q=80'],
    shades: [],
    sizes: ['50g'],
    ingredients: ['Encapsulated Retinol', 'Squalane', 'Peptides'],
    benefits: ['Smooths fine lines', 'Refines texture', 'Overnight renewal'],
    howToUse: 'Apply a pea-sized amount to clean skin at night, avoiding the eye area.',
    skinType: ['Normal', 'Mature'],
    stock: 96,
    sku: 'LUM-SK-006',
    tags: ['retinol', 'anti-aging', 'night cream'],
    isFeatured: false,
    isBestSeller: false,
    isNew: true,
  },
  {
    name: 'Aloe Soothing Toner',
    brand: 'LUMÉA',
    category: 'Skincare',
    subcategory: 'Toner',
    description:
      'An alcohol-free toner infused with aloe vera and cucumber extract that soothes, balances and preps skin for the next steps of your routine.',
    shortDescription: 'Alcohol-free soothing aloe toner',
    price: 399,
    originalPrice: 479,
    discountPercentage: 17,
    rating: 4.3,
    reviewCount: 214,
    image: 'https://images.unsplash.com/photo-1601049541289-9b1b7bbbfe19?auto=format&fit=crop&w=800&q=80',
    thumbnail: 'https://images.unsplash.com/photo-1601049541289-9b1b7bbbfe19?auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1601049541289-9b1b7bbbfe19?auto=format&fit=crop&w=800&q=80'],
    shades: [],
    sizes: ['150ml'],
    ingredients: ['Aloe Vera', 'Cucumber Extract', 'Chamomile'],
    benefits: ['Soothes skin', 'Balances pH', 'Alcohol-free'],
    howToUse: 'Sweep across face with a cotton pad after cleansing.',
    skinType: ['Sensitive', 'All'],
    stock: 175,
    sku: 'LUM-SK-007',
    tags: ['toner', 'soothing', 'aloe'],
    isFeatured: false,
    isBestSeller: false,
    isNew: false,
  },
  {
    name: 'Under Eye Brightening Gel',
    brand: 'LUMÉA',
    category: 'Skincare',
    subcategory: 'Eye Care',
    description:
      'A cooling under-eye gel with caffeine and vitamin C that reduces the appearance of puffiness and dark circles for a well-rested look.',
    shortDescription: 'Cooling caffeine under-eye gel',
    price: 699,
    originalPrice: 849,
    discountPercentage: 18,
    rating: 4.5,
    reviewCount: 231,
    image: 'https://images.unsplash.com/photo-1556228720-0b3a9c05f5cb?auto=format&fit=crop&w=800&q=80',
    thumbnail: 'https://images.unsplash.com/photo-1556228720-0b3a9c05f5cb?auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1556228720-0b3a9c05f5cb?auto=format&fit=crop&w=800&q=80'],
    shades: [],
    sizes: ['15ml'],
    ingredients: ['Caffeine', 'Vitamin C', 'Hyaluronic Acid'],
    benefits: ['Reduces puffiness', 'Brightens dark circles', 'Cooling effect'],
    howToUse: 'Dab a small amount under eyes using the metal applicator morning and night.',
    skinType: ['All'],
    stock: 140,
    sku: 'LUM-SK-008',
    tags: ['eye care', 'brightening', 'gel'],
    isFeatured: false,
    isBestSeller: false,
    isNew: false,
  },

  // ---------- Haircare ----------
  {
    name: 'Herbal Hair Serum',
    brand: 'LUMÉA',
    category: 'Haircare',
    subcategory: 'Serum',
    description:
      'A lightweight herbal serum enriched with argan and almond oil that tames frizz, adds shine and protects hair from heat damage.',
    shortDescription: 'Frizz-control herbal shine serum',
    price: 549,
    originalPrice: 649,
    discountPercentage: 15,
    rating: 4.5,
    reviewCount: 342,
    image: 'https://images.unsplash.com/photo-1608248597359-59751e041355?auto=format&fit=crop&w=800&q=80',
    thumbnail: 'https://images.unsplash.com/photo-1608248597359-59751e041355?auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1608248597359-59751e041355?auto=format&fit=crop&w=800&q=80'],
    shades: [],
    sizes: ['100ml'],
    ingredients: ['Argan Oil', 'Almond Oil', 'Vitamin E'],
    benefits: ['Controls frizz', 'Adds shine', 'Heat protection'],
    howToUse: 'Apply a few drops to damp or dry hair, focusing on mid-lengths and ends.',
    skinType: [],
    stock: 188,
    sku: 'LUM-HC-001',
    tags: ['hair serum', 'frizz control', 'shine'],
    isFeatured: true,
    isBestSeller: true,
    isNew: false,
  },
  {
    name: 'Keratin Smoothing Shampoo',
    brand: 'LUMÉA',
    category: 'Haircare',
    subcategory: 'Shampoo',
    description:
      'A sulfate-free shampoo with keratin proteins that smooths the hair cuticle, reduces frizz and strengthens strands with every wash.',
    shortDescription: 'Sulfate-free keratin smoothing shampoo',
    price: 449,
    originalPrice: 549,
    discountPercentage: 18,
    rating: 4.4,
    reviewCount: 267,
    image: 'https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?auto=format&fit=crop&w=800&q=80',
    thumbnail: 'https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?auto=format&fit=crop&w=800&q=80'],
    shades: [],
    sizes: ['250ml'],
    ingredients: ['Keratin', 'Coconut Oil', 'Biotin'],
    benefits: ['Smooths cuticle', 'Strengthens hair', 'Sulfate-free'],
    howToUse: 'Lather onto wet hair, massage into scalp and rinse thoroughly.',
    skinType: [],
    stock: 210,
    sku: 'LUM-HC-002',
    tags: ['shampoo', 'keratin', 'smoothing'],
    isFeatured: false,
    isBestSeller: true,
    isNew: false,
  },
  {
    name: 'Deep Repair Hair Mask',
    brand: 'LUMÉA',
    category: 'Haircare',
    subcategory: 'Treatment',
    description:
      'An intensive weekly hair mask formulated with shea butter and protein complex to repair damage and restore softness to dry, brittle hair.',
    shortDescription: 'Intensive weekly repair hair mask',
    price: 749,
    originalPrice: 899,
    discountPercentage: 17,
    rating: 4.6,
    reviewCount: 195,
    image: 'https://images.unsplash.com/photo-1527799820374-dcf8d9d4a388?auto=format&fit=crop&w=800&q=80',
    thumbnail: 'https://images.unsplash.com/photo-1527799820374-dcf8d9d4a388?auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1527799820374-dcf8d9d4a388?auto=format&fit=crop&w=800&q=80'],
    shades: [],
    sizes: ['200g'],
    ingredients: ['Shea Butter', 'Protein Complex', 'Argan Oil'],
    benefits: ['Repairs damage', 'Restores softness', 'Reduces breakage'],
    howToUse: 'Apply generously to washed hair, leave for 15 minutes, then rinse.',
    skinType: [],
    stock: 118,
    sku: 'LUM-HC-003',
    tags: ['hair mask', 'repair', 'treatment'],
    isFeatured: false,
    isBestSeller: false,
    isNew: true,
  },
  {
    name: 'Volumizing Conditioner',
    brand: 'LUMÉA',
    category: 'Haircare',
    subcategory: 'Conditioner',
    description:
      'A lightweight conditioner that detangles and adds volume without weighing hair down, leaving it bouncy and full of body.',
    shortDescription: 'Lightweight volumizing conditioner',
    price: 429,
    originalPrice: 499,
    discountPercentage: 14,
    rating: 4.3,
    reviewCount: 156,
    image: 'https://images.unsplash.com/photo-1519735777090-ec97162dc266?auto=format&fit=crop&w=800&q=80',
    thumbnail: 'https://images.unsplash.com/photo-1519735777090-ec97162dc266?auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1519735777090-ec97162dc266?auto=format&fit=crop&w=800&q=80'],
    shades: [],
    sizes: ['250ml'],
    ingredients: ['Panthenol', 'Rice Protein', 'Biotin'],
    benefits: ['Adds volume', 'Detangles', 'Lightweight'],
    howToUse: 'Apply to mid-lengths and ends after shampooing, rinse after 2-3 minutes.',
    skinType: [],
    stock: 165,
    sku: 'LUM-HC-004',
    tags: ['conditioner', 'volumizing'],
    isFeatured: false,
    isBestSeller: false,
    isNew: false,
  },
  {
    name: 'Scalp Detox Exfoliating Scrub',
    brand: 'LUMÉA',
    category: 'Haircare',
    subcategory: 'Scalp Care',
    description:
      'A pre-shampoo scalp scrub with sea salt and tea tree oil that removes buildup, exfoliates the scalp and promotes a healthier foundation for hair growth.',
    shortDescription: 'Sea salt scalp exfoliating scrub',
    price: 499,
    originalPrice: 599,
    discountPercentage: 17,
    rating: 4.4,
    reviewCount: 132,
    image: 'https://images.unsplash.com/photo-1559599101-f09722fb4948?auto=format&fit=crop&w=800&q=80',
    thumbnail: 'https://images.unsplash.com/photo-1559599101-f09722fb4948?auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1559599101-f09722fb4948?auto=format&fit=crop&w=800&q=80'],
    shades: [],
    sizes: ['150g'],
    ingredients: ['Sea Salt', 'Tea Tree Oil', 'Peppermint Extract'],
    benefits: ['Removes buildup', 'Exfoliates scalp', 'Refreshes'],
    howToUse: 'Massage onto damp scalp before shampooing, then rinse thoroughly.',
    skinType: [],
    stock: 89,
    sku: 'LUM-HC-005',
    tags: ['scalp care', 'exfoliating', 'detox'],
    isFeatured: false,
    isBestSeller: false,
    isNew: true,
  },

  // ---------- Fragrance ----------
  {
    name: 'Rose Eau De Parfum',
    brand: 'LUMÉA',
    category: 'Fragrance',
    subcategory: 'Eau de Parfum',
    description:
      'A romantic eau de parfum built around a heart of Bulgarian rose, layered with soft musk and warm amber for a long-lasting, elegant signature scent.',
    shortDescription: 'Romantic rose and amber eau de parfum',
    price: 1899,
    originalPrice: 2299,
    discountPercentage: 17,
    rating: 4.7,
    reviewCount: 289,
    image: 'https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=800&q=80',
    thumbnail: 'https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=800&q=80'],
    shades: [],
    sizes: ['50ml', '100ml'],
    ingredients: ['Bulgarian Rose', 'White Musk', 'Amber'],
    benefits: ['Long-lasting', 'Elegant scent', 'Layerable'],
    howToUse: 'Spray onto pulse points such as wrists and neck for lasting wear.',
    skinType: [],
    stock: 112,
    sku: 'LUM-FR-001',
    tags: ['perfume', 'rose', 'edp'],
    isFeatured: true,
    isBestSeller: true,
    isNew: false,
  },
  {
    name: 'Citrus Bloom Eau De Toilette',
    brand: 'LUMÉA',
    category: 'Fragrance',
    subcategory: 'Eau de Toilette',
    description:
      'A fresh, energizing eau de toilette with notes of bergamot, mandarin and white florals, perfect for a bright everyday spritz.',
    shortDescription: 'Fresh citrus and floral eau de toilette',
    price: 1299,
    originalPrice: 1549,
    discountPercentage: 16,
    rating: 4.5,
    reviewCount: 174,
    image: 'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&w=800&q=80',
    thumbnail: 'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&w=800&q=80'],
    shades: [],
    sizes: ['50ml', '100ml'],
    ingredients: ['Bergamot', 'Mandarin', 'White Florals'],
    benefits: ['Fresh scent', 'Energizing', 'Everyday wear'],
    howToUse: 'Spritz onto pulse points; reapply as needed throughout the day.',
    skinType: [],
    stock: 134,
    sku: 'LUM-FR-002',
    tags: ['perfume', 'citrus', 'edt'],
    isFeatured: false,
    isBestSeller: false,
    isNew: true,
  },
  {
    name: 'Velvet Oud Parfum',
    brand: 'LUMÉA',
    category: 'Fragrance',
    subcategory: 'Parfum',
    description:
      'A rich, opulent parfum combining smoky oud, warm sandalwood and spicy saffron for a deep, long-lasting evening fragrance.',
    shortDescription: 'Rich smoky oud and sandalwood parfum',
    price: 2499,
    originalPrice: 2999,
    discountPercentage: 17,
    rating: 4.8,
    reviewCount: 98,
    image: 'https://images.unsplash.com/photo-1523293182086-7651a899d37f?auto=format&fit=crop&w=800&q=80',
    thumbnail: 'https://images.unsplash.com/photo-1523293182086-7651a899d37f?auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1523293182086-7651a899d37f?auto=format&fit=crop&w=800&q=80'],
    shades: [],
    sizes: ['50ml'],
    ingredients: ['Oud', 'Sandalwood', 'Saffron'],
    benefits: ['Rich, deep scent', 'Long-lasting', 'Evening wear'],
    howToUse: 'Apply sparingly to pulse points for a lasting, intimate scent trail.',
    skinType: [],
    stock: 62,
    sku: 'LUM-FR-003',
    tags: ['perfume', 'oud', 'parfum'],
    isFeatured: true,
    isBestSeller: false,
    isNew: false,
  },

  // ---------- Body Care ----------
  {
    name: 'Shea Butter Body Lotion',
    brand: 'LUMÉA',
    category: 'Body Care',
    subcategory: 'Body Lotion',
    description:
      'A rich, fast-absorbing body lotion with shea butter and cocoa butter that deeply moisturizes and leaves skin soft for up to 48 hours.',
    shortDescription: '48-hour moisture shea butter lotion',
    price: 449,
    originalPrice: 549,
    discountPercentage: 18,
    rating: 4.5,
    reviewCount: 312,
    image: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&w=800&q=80',
    thumbnail: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&w=800&q=80'],
    shades: [],
    sizes: ['200ml', '400ml'],
    ingredients: ['Shea Butter', 'Cocoa Butter', 'Vitamin E'],
    benefits: ['48-hour hydration', 'Fast-absorbing', 'Softens skin'],
    howToUse: 'Massage generously over body after a shower or bath.',
    skinType: ['Dry', 'Normal'],
    stock: 240,
    sku: 'LUM-BC-001',
    tags: ['body lotion', 'shea butter', 'moisturizer'],
    isFeatured: false,
    isBestSeller: true,
    isNew: false,
  },
  {
    name: 'Coffee Bean Body Scrub',
    brand: 'LUMÉA',
    category: 'Body Care',
    subcategory: 'Scrub',
    description:
      'An invigorating body scrub made with ground coffee and coconut oil that exfoliates dead skin, boosts circulation and reveals smoother skin.',
    shortDescription: 'Invigorating coffee and coconut body scrub',
    price: 549,
    originalPrice: 649,
    discountPercentage: 15,
    rating: 4.6,
    reviewCount: 201,
    image: 'https://images.unsplash.com/photo-1563178406-4cdc2923acbc?auto=format&fit=crop&w=800&q=80',
    thumbnail: 'https://images.unsplash.com/photo-1563178406-4cdc2923acbc?auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1563178406-4cdc2923acbc?auto=format&fit=crop&w=800&q=80'],
    shades: [],
    sizes: ['250g'],
    ingredients: ['Ground Coffee', 'Coconut Oil', 'Brown Sugar'],
    benefits: ['Exfoliates', 'Boosts circulation', 'Smooths skin'],
    howToUse: 'Massage onto damp skin in circular motions, then rinse off.',
    skinType: [],
    stock: 178,
    sku: 'LUM-BC-002',
    tags: ['scrub', 'exfoliating', 'coffee'],
    isFeatured: false,
    isBestSeller: false,
    isNew: false,
  },
  {
    name: 'Whipped Body Butter',
    brand: 'LUMÉA',
    category: 'Body Care',
    subcategory: 'Body Butter',
    description:
      'A luxuriously whipped body butter with mango and shea that melts into skin instantly, providing intense nourishment without a greasy feel.',
    shortDescription: 'Whipped mango and shea body butter',
    price: 599,
    originalPrice: 699,
    discountPercentage: 14,
    rating: 4.7,
    reviewCount: 187,
    image: 'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&w=800&q=80',
    thumbnail: 'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&w=800&q=80'],
    shades: [],
    sizes: ['200g'],
    ingredients: ['Mango Butter', 'Shea Butter', 'Coconut Oil'],
    benefits: ['Intense nourishment', 'Non-greasy', 'Melts into skin'],
    howToUse: 'Scoop a small amount and massage into skin until fully absorbed.',
    skinType: ['Dry'],
    stock: 143,
    sku: 'LUM-BC-003',
    tags: ['body butter', 'moisturizer', 'mango'],
    isFeatured: true,
    isBestSeller: false,
    isNew: true,
  },
  {
    name: 'Refreshing Body Wash',
    brand: 'LUMÉA',
    category: 'Body Care',
    subcategory: 'Body Wash',
    description:
      'A gentle, sulfate-free body wash infused with cucumber and mint extract that cleanses and refreshes skin without stripping moisture.',
    shortDescription: 'Sulfate-free cucumber mint body wash',
    price: 349,
    originalPrice: 429,
    discountPercentage: 19,
    rating: 4.4,
    reviewCount: 256,
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=800&q=80',
    thumbnail: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=800&q=80'],
    shades: [],
    sizes: ['300ml'],
    ingredients: ['Cucumber Extract', 'Mint Extract', 'Glycerin'],
    benefits: ['Gentle cleansing', 'Refreshing', 'Sulfate-free'],
    howToUse: 'Lather onto wet skin with a loofah, then rinse thoroughly.',
    skinType: ['All'],
    stock: 230,
    sku: 'LUM-BC-004',
    tags: ['body wash', 'cleanser', 'refreshing'],
    isFeatured: false,
    isBestSeller: false,
    isNew: false,
  },

  // ---------- Beauty Tools ----------
  {
    name: 'Rose Quartz Facial Roller',
    brand: 'LUMÉA',
    category: 'Beauty Tools',
    subcategory: 'Facial Tools',
    description:
      'A genuine rose quartz facial roller that gently massages the face to reduce puffiness, boost circulation and enhance product absorption.',
    shortDescription: 'Rose quartz facial massage roller',
    price: 799,
    originalPrice: 999,
    discountPercentage: 20,
    rating: 4.5,
    reviewCount: 134,
    image: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=800&q=80',
    thumbnail: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=800&q=80'],
    shades: [],
    sizes: ['One Size'],
    ingredients: [],
    benefits: ['Reduces puffiness', 'Boosts circulation', 'Enhances absorption'],
    howToUse: 'Roll gently upward and outward across cleansed skin daily.',
    skinType: [],
    stock: 95,
    sku: 'LUM-BT-001',
    tags: ['facial roller', 'rose quartz', 'tools'],
    isFeatured: false,
    isBestSeller: false,
    isNew: true,
  },
  {
    name: 'Professional Makeup Brush Set',
    brand: 'LUMÉA',
    category: 'Beauty Tools',
    subcategory: 'Brushes',
    description:
      'A complete 12-piece makeup brush set with soft synthetic bristles for flawless application of foundation, powder, blush and eyeshadow.',
    shortDescription: '12-piece soft synthetic brush set',
    price: 1199,
    originalPrice: 1499,
    discountPercentage: 20,
    rating: 4.6,
    reviewCount: 221,
    image: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&w=800&q=80',
    thumbnail: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&w=800&q=80'],
    shades: [],
    sizes: ['12-piece set'],
    ingredients: [],
    benefits: ['Flawless application', 'Soft bristles', 'Complete set'],
    howToUse: 'Select the appropriate brush for each product and application area.',
    skinType: [],
    stock: 108,
    sku: 'LUM-BT-002',
    tags: ['brushes', 'makeup tools', 'set'],
    isFeatured: true,
    isBestSeller: true,
    isNew: false,
  },
  {
    name: 'Blending Beauty Sponge Duo',
    brand: 'LUMÉA',
    category: 'Beauty Tools',
    subcategory: 'Sponges',
    description:
      'A latex-free beauty sponge duo that expands when damp to blend foundation, concealer and cream products seamlessly into skin.',
    shortDescription: 'Latex-free blending sponge duo',
    price: 399,
    originalPrice: 499,
    discountPercentage: 20,
    rating: 4.4,
    reviewCount: 176,
    image: 'https://images.unsplash.com/photo-1583241800698-9c2e2f4f6c7d?auto=format&fit=crop&w=800&q=80',
    thumbnail: 'https://images.unsplash.com/photo-1583241800698-9c2e2f4f6c7d?auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1583241800698-9c2e2f4f6c7d?auto=format&fit=crop&w=800&q=80'],
    shades: ['Pink', 'Peach'],
    sizes: ['2-piece set'],
    ingredients: [],
    benefits: ['Seamless blending', 'Latex-free', 'Reusable'],
    howToUse: 'Dampen the sponge and bounce onto skin to blend products evenly.',
    skinType: [],
    stock: 199,
    sku: 'LUM-BT-003',
    tags: ['beauty sponge', 'blending', 'tools'],
    isFeatured: false,
    isBestSeller: false,
    isNew: false,
  },
  {
    name: 'LED Facial Cleansing Brush',
    brand: 'LUMÉA',
    category: 'Beauty Tools',
    subcategory: 'Facial Tools',
    description:
      'A rechargeable silicone facial cleansing brush with gentle vibration and LED light therapy to deeply cleanse pores and improve skin texture.',
    shortDescription: 'Rechargeable LED silicone cleansing brush',
    price: 1799,
    originalPrice: 2199,
    discountPercentage: 18,
    rating: 4.5,
    reviewCount: 87,
    image: 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796?auto=format&fit=crop&w=800&q=80',
    thumbnail: 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796?auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1512496015851-a90fb38ba796?auto=format&fit=crop&w=800&q=80'],
    shades: ['White', 'Blush Pink'],
    sizes: ['One Size'],
    ingredients: [],
    benefits: ['Deep cleansing', 'LED light therapy', 'Rechargeable'],
    howToUse: 'Apply cleanser and glide the brush over damp skin in circular motions.',
    skinType: [],
    stock: 58,
    sku: 'LUM-BT-004',
    tags: ['cleansing brush', 'led', 'tools'],
    isFeatured: true,
    isBestSeller: false,
    isNew: true,
  },
  {
    name: 'Precision Eyebrow Razor Trio',
    brand: 'LUMÉA',
    category: 'Beauty Tools',
    subcategory: 'Grooming',
    description:
      'A set of three precision eyebrow razors for effortlessly shaping brows and removing peach fuzz for a smooth makeup base.',
    shortDescription: '3-piece precision brow razor set',
    price: 249,
    originalPrice: 299,
    discountPercentage: 17,
    rating: 4.2,
    reviewCount: 143,
    image: 'https://images.unsplash.com/photo-1527799820374-dcf8d9d4a388?auto=format&fit=crop&w=800&q=80',
    thumbnail: 'https://images.unsplash.com/photo-1527799820374-dcf8d9d4a388?auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1527799820374-dcf8d9d4a388?auto=format&fit=crop&w=800&q=80'],
    shades: [],
    sizes: ['3-piece set'],
    ingredients: [],
    benefits: ['Precise shaping', 'Removes peach fuzz', 'Travel-friendly'],
    howToUse: 'Glide gently along the brow edges or face in short, light strokes.',
    skinType: [],
    stock: 220,
    sku: 'LUM-BT-005',
    tags: ['eyebrow razor', 'grooming', 'tools'],
    isFeatured: false,
    isBestSeller: false,
    isNew: false,
  },
  {
    name: 'Jade Gua Sha Stone',
    brand: 'LUMÉA',
    category: 'Beauty Tools',
    subcategory: 'Facial Tools',
    description:
      'An authentic jade gua sha stone designed to sculpt facial contours, relieve tension and promote lymphatic drainage as part of a daily skincare ritual.',
    shortDescription: 'Authentic jade sculpting gua sha stone',
    price: 699,
    originalPrice: 849,
    discountPercentage: 18,
    rating: 4.6,
    reviewCount: 112,
    image: 'https://images.unsplash.com/photo-1608248597359-59751e041355?auto=format&fit=crop&w=800&q=80',
    thumbnail: 'https://images.unsplash.com/photo-1608248597359-59751e041355?auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1608248597359-59751e041355?auto=format&fit=crop&w=800&q=80'],
    shades: [],
    sizes: ['One Size'],
    ingredients: [],
    benefits: ['Sculpts contours', 'Relieves tension', 'Promotes drainage'],
    howToUse: 'Glide along the jawline, cheeks and forehead with light upward strokes.',
    skinType: [],
    stock: 76,
    sku: 'LUM-BT-006',
    tags: ['gua sha', 'jade', 'facial tools'],
    isFeatured: false,
    isBestSeller: false,
    isNew: false,
  },
];

module.exports = { categories, products };